version: '3'

services:
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/create-people-table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - node-mysql-net
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  server:
    build:
      context: .
      dockerfile: Dockerfile-node
      target: prod
    image: fcoromoto/node-nginx-server
    networks:
      - node-mysql-net
      - proxy-net
    entrypoint: wait-for-it database:3306 -- npm run start
    depends_on:
      - database

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: fcoromoto/nginx-proxy
    networks:
      - proxy-net
    ports:
      - "8080:80"

networks:
  node-mysql-net:
  proxy-net:
