FROM node:alpine3.18

RUN apk update && \
    apk add --no-cache --upgrade bash && \
    apk add --no-cache wget && \
    wget -q -O /usr/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && \
    chmod +x /usr/bin/wait-for-it

USER node

WORKDIR app/

COPY app/package.json .

RUN npm install

COPY app/index.js .

EXPOSE 3000

CMD ["npm" , "start" ]
